- name: Create folders for captures
  shell: "mkdir -p {{target_dir}}"
  with_items: "{{motion.cameras.keys()}}"
  vars:
    target_dir: "{{motion.cameras[item]['target_dir']}}"
  when: "'target_dir' in motion.cameras[item].keys()"

- name: Clean old motion config
  shell: rm -f /etc/motion/*

- name: Merge config
  set_fact:
    tmp_conf: "{{base_motion_conf | combine(motion.conf | default(default_motion_conf))}}"
- name: Merge config
  set_fact:
    motion: "{{motion|combine({'conf':tmp_conf})}}"
- name: Describe config
  debug: var=motion

- name: Configure motion base config
  # copy:
  #   content: |-
  #     {{motion.base_conf}}
  #     {% for cam_name in motion.cameras.keys() %}
  #     thread /etc/motion/{{cam_name}}.conf
  #     {%endfor%}
  #   dest: "{{item}}"
  ansible.builtin.template:
    src: "motion.conf.j2"
    # dest: "{{motion_conf_file}}"
    # validate: /usr/sbin/visudo -cf %s
    dest: "{{item}}"
  with_items:
    - "{{motion_conf_file}}"

- name: Configure motion cameras
  copy:
    content: |-
      {% for k,v in motion.cameras[item].items() %}
      {{k}} {{v}}
      {%endfor%}
    dest: "/etc/motion/{{item}}.conf"
  with_items: "{{motion.cameras.keys()}}"

- name: Daemonize motion
  import_role:
    name: elo.supercomposer
  vars:
    supervisor_service: "motion"
    supervisor_app_config: |-
      # Help for motion CLI flags:
      #   -n			Run in non-daemon mode.
      #   -c config		Full path and filename of config file.
      #   -d level		Log level (1-9) (EMG, ALR, CRT, ERR, WRN, NTC, INF, DBG, ALL). default: 6 / NTC.
      #   -m			Disable motion detection at startup.
      [program:motion]
      command=motion -n -m -c /etc/motion/motion.conf
      directory=/home/{{ansible_user}}
      autostart=true
      autorestart=true
      user={{ansible_user}}
      environment=HOME="/home/{{ansible_user}}",USER="{{ansible_user}}"
