- name: Install v4l tools
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - v4l-utils
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Lookup current cameras
  shell: v4l2-ctl --list-devices
  register: cam_out
  ignore_errors: yes

- name: Describe cameras
  debug: var=cam_out
